/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_sun_correspond_JNIToC */

#ifndef _Included_com_sun_correspond_JNIToC
#define _Included_com_sun_correspond_JNIToC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_sun_correspond_JNIToC
 * Method:    setInformation
 * Signature: (Ljava/lang/String;IIF)V
 */
JNIEXPORT void JNICALL Java_com_sun_correspond_JNIToC_setInformation
  (JNIEnv *, jclass, jstring, jint, jint, jfloat);

/*
 * Class:     com_sun_correspond_JNIToC
 * Method:    getPictureInfo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_sun_correspond_JNIToC_getPictureInfo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
